### ISSUE TITLE
does not honour search paths

### ISSUE THREAD

**Issue by umlaeute** [porres/completion-plugin#23]
it seems that you intentionally ignore all search-paths that Pd knows about, in favour of one that is not guaranteed to be there (see #22 ).

https://github.com/porres/completion-plugin/blob/c688968d641cf3c5e289f8e611552cad0bf5348e/completion-plugin.tcl#L624-L628

why do you actively disable support for the *default* search paths and for those search-paths that the user explicitely included in their configuration?

**Comment by umlaeute** [comment]
> why do you actively disable support for the default search path...

vs 

> let's just use default externals folder

that there are a couple of *default* folders and docsdir is not among them.

we do have a mechanism for docsdir (and that is cool), but it is totally optional.

the actual *default* paths (as defined by the Pd-core) are `$::sys_staticpath`

**Comment by porres** [comment]
> it seems that you intentionally ignore all search-paths that Pd knows about, in favour of one that is not guaranteed to be there (see https://github.com/porres/completion-plugin/issues/22 ).

I'll also refer to my answer in https://github.com/porres/completion-plugin/issues/22 , see --> https://github.com/porres/completion-plugin/issues/22#issuecomment-1474868174

Most of my reasonings come from what I said there...

In short, the old way had some issues with efficiency, redundancy and also collected unwanted duplicates or garbage. This new way is much simpler and works for the new way Pd suggests for years now. I have the old way (a 'deep scan') now restored in 0.49.1 as a fallback for when you don't have "pd_docsdir" set...

I don't know yet of a good and sane way to deal with a 'deep scan' and I guess I can include it in the plugin preferences as a "non recommended" practice or something for "power users" that know what they're doing and I can mention the caveats in the manual.

**Comment by porres** [comment]
> I don't know yet of a good and sane way to deal with a 'deep scan' and I guess I can include it in the plugin preferences as a "non recommended" practice or something for "power users" that know what they're doing and I can mention the caveats in the manual.

The best thing to do is actually make a deep scan that doesn't give us "garbage". I am trying hard to get rid of settings settings, not include more stuff

**Comment by porres** [comment]
closing in favor of https://github.com/porres/completion-plugin/issues/30

**Comment by umlaeute** [comment]
I disagree that this is the same as #30.
#30 is about an improvement (better deep scan), while this is a bug/regression (completions no longer take my not-nested libraries installed in my search paths into account)

**Comment by porres** [comment]
> completions no longer take my not-nested libraries installed in my search paths into account

right now, with the last update and current master, when pd_docsdir fails and it does the same old 'deep scan', is this still happening (in other words, is the regression still there)? What do you mean about "not-nested libraries"?

**Comment by umlaeute** [comment]
> right now, with the last update and current master, when pd_docsdir fails

And if pd_docsdir does not fail?

I'm aware that I am one of the few who do not use the docsdir at all (I'm aware of others nevertheless).

However the search paths issue is not related to using docsdir.
You can use docsdir, and still prefer to install Pd libraries with `apt-get`.
Or use docsdir for *your* Pd-stuff, but tell deken to install to some other user-specific (default like %AppData%; or non-default) directory.

I would like to find all the objects that are found in my search paths. ( So actually, I would also like to find those added via startup flags and available in `sys_tmpdir` as well)

**Comment by porres** [comment]
Yeah, my plan is to work now on this deeper scan without getting unwanted noise, but this is part of #30 

>  I would also like to find those added via startup flags and available in sys_tmpdir as well

noted in #30
