### ISSUE TITLE
navigate suggestions with arrow up/down

### ISSUE THREAD

**Issue by umlaeute** [porres/completion-plugin#25]
this is probably very minor (for practical uses), but while testing i find it slightly annoying that i cannot use the arrow keys <kbd>↑</kbd>  resp <kbd>↓</kbd> for navigating the list.

**Comment by porres** [comment]
well, you're actually supposed to and I can do it here... so seems like a linux bug or something

**Comment by umlaeute** [comment]
doh. now it works.

i'm sure it did not but can no longer reproduce (both with git `HEAD` and 0.48.0)....
