### ISSUE TITLE
click/hitting enter should also create the object

### ISSUE THREAD

**Issue by porres** [porres/completion-plugin#28]
right now it just replaces the text with the selection, you still need to click outside or hit 'Tab' key to create the object.

I thought that doing  _::completion::sendKeyDownAndUp 9_ after the selection would send a Tab key to Pd and create the object but it didn't work, any idea why and what I should do instead @umlaeute / @sebshader ?

**Comment by porres** [comment]
while we're at it, a "right arrow" could also be used for this...

**Comment by umlaeute** [comment]
> right now it just replaces the text with the selection, you still need to click outside or hit 'Tab' key to create the object.

Isn't that a feature?
After auto-completing `[pack]` I actually want to be able to add some arguments before the object creates...

**Comment by porres** [comment]
> After auto-completing [pack] I actually want to be able to add some arguments before the object creates...

yeah, that makes sense
